Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Shopping_list_website.Models;

namespace Shopping_list_website.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly ShoppingCartDbContext _context;

        public HomeController(ILogger<HomeController> logger, ShoppingCartDbContext context)
        {
            _logger = logger;
            _context = context;
        }

        public IActionResult Index()
        {
            // Set the title name in shared.
            ViewData["Title"] = "Home";

            // Displays an error message to the user.
            ViewBag.ErrorMessage = HttpContext.Session.GetString("ErrorMsg");
            // Used to welcome the user by name.
            ViewBag.Username = HttpContext.Session.GetString("Username");

            // Check if the user is signed in
            Account? account = _context.Accounts.Find(HttpContext.Session.GetInt32("UserId"));

            if (account != null)
            {
                // check if the user has selected an account, use eager loading to make it load the lines field in, and also load the items in from lines.
                var selectedCart = _context.ShoppingCarts
                   .Include(cart => cart.Lines)
                   .ThenInclude(line => line.Item)
                   .FirstOrDefault(cart => cart.Id == account.SelectedCart);

                if (selectedCart != null)
                {
                    // Give the view the selected carts name.
                    ViewData["SelectedCart"] = selectedCart.Name;

                    /*      // Old code used to display the users shopping cart items, which has been replaced with a modal.
                    if (selectedCart.Lines != null)
                    {
                        // Get the contents from selected cart.
                        var cartContents = selectedCart.Lines.Select(l => l.Item).ToList();

                        // Store the user's items and all the items into a tuple, to allow the view to display the users shopping cart contents aswell as the items that may be added.
                        Tuple<IEnumerable<Item>, IEnumerable<Item>> itemData = new Tuple<IEnumerable<Item>, IEnumerable<Item>>(_context.Items, cartContents);

                        return View(itemData);
                    }*/

                }
            }

            // Pass items into the view, the second value of the tuple used to be used for sending the items
            // inside the user's cart to the view aswell, but it was replaced by a modal.
            return View(new Tuple<IEnumerable<Item>, IEnumerable<Item>?>(_context.Items, null));

        }
        /*
        public IActionResult AddItemToCart([FromQuery] int? itemId)
        {
            if (itemId == null)
                return BadRequest("missing itemId");

            var userId = HttpContext.Session.GetInt32("UserId");

            // Find the currently logged in user.
            var account = _context.Accounts.Find(userId);

            // Check if the account has a shopping cart selected, if not return a bad request.
            if (account != null && account.SelectedCart != null)
            {
                // Get the selected item from the database using it's id
                var item = _context.Items.Find(itemId);

                try
                {
                    // Try to find a shopping cart line which connects the current shopping cart and the item being added.
                    var line = _context.ShoppingCartLines.Where(l => l.ItemId == itemId && l.ShoppingCartId == account.SelectedCart).FirstOrDefault();

                    // If a line already exists increase its quantity by one.
                    if (line != null)
                    {
                        line.Quantity += 1;
                    }
                    // Otherwise create a new shopping cart line to connect the shopping cart and the item.
                    else
                    {
                        // Make a new shopping cart line to connect the item with the shopping cart.
                        line = new ShoppingCartLine();
                        line.ShoppingCartId = (int)account.SelectedCart;
                        line.ItemId = item.Id;
                        line.Quantity = 1;
                        _context.Add(line);
                    }


                    _context.SaveChanges();

                    return Ok("Item added.");
                }

                catch
                {
                    return StatusCode(500, "Error adding item to shopping list.");

                }

            }
            else
                return BadRequest("No shopping cart selected.");

        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
        */
    }
}

Controllers/SettingsController.cs
using Microsoft.AspNetCore.Mvc;


namespace Shopping_list_website.Controllers
{
    public class SettingsController : Controller
    {

        [HttpPost]
        public async Task<IActionResult> SetTheme([FromBody] ThemeSetting setting)
        {
            // Set the current theme based off what the request specified.
            HttpContext.Session.SetString("Theme", setting.Theme);
            return Ok();
        }

        [HttpGet]
        public string? GetTheme()
        {
            // Get the current theme from session and return it to the caller.
            string? theme = HttpContext.Session.GetString("Theme");

            return theme;
        }

        public IActionResult Index()
        {
            return View();
        }
    }

    // This class is used for mapping for the controller request.
    public class ThemeSetting
    {
        public string Theme { get; set; }
    }

}

Controllers/ShoppingCartController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Shopping_list_website.Models;

namespace Shopping_list_website.Controllers
{
    public class ShoppingCartController : Controller
    {
        private readonly ShoppingCartDbContext _context;
        public ShoppingCartController(ShoppingCartDbContext context) { _context = context; }

        public IActionResult Index()
        {
            ViewData["Title"] = "Shopping cart";

            try
            {
                string? user = HttpContext.Session.GetString("Username");

                // If the user has not logged in redirect back to home and store the error message in session, so the home controller can read it and then put it in viewbag and display it in html.
                if (user == null)
                {
                    HttpContext.Session.SetString("ErrorMsg", "Please log in to access the shopping cart page");
                    return Redirect("Home/Index");
                }

                // Get the user's account from the database.
                Account userAccount = _context.Accounts.Where(a => a.Email.Equals(user)).Include(u => u.ShoppingCarts).FirstOrDefault();

                return View(userAccount);
            }

            catch
            {

                return View(null);
            }


        }
        [HttpGet]
        public IActionResult GetPartialCartItems()
        {
            string? user = HttpContext.Session.GetString("Username");

            // Get the user's account from the database.
            Account? userAccount = _context.Accounts.Where(a => a.Email.Equals(user)).Include(a => a.ShoppingCarts).FirstOrDefault();


            if (userAccount != null)
            {
                // If the user account was found, find the users selected cart, include the lines and include the items from the lines.
                ShoppingCart? cart = _context.ShoppingCarts.Where(c => c.Id == userAccount.SelectedCart)
                    .Include(c => c.Lines)
                    .ThenInclude(l => l.Item)
                    .FirstOrDefault();

                // If a cart was found return a partial page to be displayed inside the main page.
                // The partial page being sent will display all the items inside the cart.
                if (cart != null)
                {
                    return PartialView("_CartItemsPartial", cart);
                }
                else
                {
                    // If the user does not have a selected cart try to set the user's selected cart to the first cart in the user's shopping carts.
                    var carts = _context.ShoppingCarts.Where(c => c.AccountId == userAccount.Id).Include(c => c.Lines).ThenInclude(l => l.Item);
                    if (carts != null)
                    {
                        cart = carts.FirstOrDefault();
                        userAccount.SelectedCart = cart.Id;
                        _context.SaveChanges();
                        return PartialView("_CartItemsPartial", cart);
                    }
                }

                return BadRequest("User does not have any carts");
            }

            return BadRequest("user not signed in");
        }

        [HttpGet]
        public IActionResult GetCartContents([FromQuery] int cartId)
        {
            // Extract the items out of the cart Id provided and send them to the partial view.

            // Get the cart, include the shopping cart lines, and the items from those lines.
            var cart = _context.ShoppingCarts.Where(c => c.Id == cartId).Include(c => c.Lines).ThenInclude(l => l.Item).FirstOrDefault();

            // Get the currently signed in user from session
            var userId = HttpContext.Session.GetInt32("UserId");
            var account = _context.Accounts.Find(userId);


            if (cart != null)
            {
                // Get all the items out of the cart and send them to the view.
                if (cart.Lines != null)
                {
                    return PartialView("_CartItemsPartialMultiColumn", cart);
                }
            }

            return PartialView("_CartItemsPartialMultiColumn", null);
        }

        [HttpPut]
        public IActionResult UpdateSelectedCart([FromQuery] int? cartId)
        {
            // Get the user from session
            var userId = HttpContext.Session.GetInt32("UserId");

            var account = _context.Accounts.Find(userId);

            // If the user is signed in update their selected cart with the one passed in to the method.
            if (account != null)
            {
                account.SelectedCart = cartId;
                _context.SaveChanges();
                return Ok("Selected cart updated");
            }

            return StatusCode(500, "Error user not signed in");
        }

        [HttpPost]
        public IActionResult MakeNewShoppingCart([FromQuery] string cartName)
        {
            if (cartName == null)
            {
                return BadRequest();
            }

            if (ModelState.IsValid)
            {
                //Create a new shopping based off of the name the user gave it.
                var cart = new ShoppingCart();
                cart.Name = cartName;

                // Get the account of the user who made the cart.
                string username = HttpContext.Session.GetString("Username");

                var userAccount = _context.Accounts.Where(a => a.Email.Equals(username)).FirstOrDefault();


                // Set the created date to now.
                cart.DateCreated = DateTime.Now;

                // Add the cart to the database
                _context.ShoppingCarts.Add(cart);

                // Link the cart up with it's owner
                cart.AccountId = userAccount.Id;
                cart.Account = userAccount;


                if (userAccount.ShoppingCarts == null)
                    userAccount.ShoppingCarts = new List<ShoppingCart>();

                // Add the newly created cart to the user and save to database.
                userAccount.ShoppingCarts.Add(cart);
                _context.Update(userAccount);
                _context.SaveChanges();

                return Ok();
            }

            return BadRequest();
        }

        [HttpDelete]
        public IActionResult DeleteShoppingCart([FromQuery] int? cartId)
        {
            if (cartId == null)
                return BadRequest();
            // Find the cart based off of it's id.
            var cart = _context.ShoppingCarts.Where(c => c.Id == cartId).FirstOrDefault();

            // Delete it
            _context.ShoppingCarts.Remove(cart);

            // Find the user who has the cart was their selected cart and remove it.
            var accountWithCart = _context.Accounts.Where(a => a.SelectedCart == cartId).FirstOrDefault();
            if (accountWithCart != null)
                accountWithCart.SelectedCart = null;

            _context.SaveChanges();

            return Ok("cart deleted");
        }

        [HttpPost]
        public IActionResult AddItem([FromQuery] int? itemId)
        {
            if (itemId == null)
                return BadRequest("No item id given");

            int? userId = HttpContext.Session.GetInt32("UserId");

            // Get the user's account from the database.
            Account userAccount = _context.Accounts.Find(userId);

            if (userAccount != null)
            {
                ShoppingCart? selectedCart = _context.ShoppingCarts.Find(userAccount.SelectedCart);

                if (selectedCart != null)
                {
                    // Get the Shopping cart line which connects the item being added and the selected cart if it exists.
                    var itemLine = _context.ShoppingCartLines.Where(l => l.ShoppingCartId == selectedCart.Id && l.ItemId == itemId).FirstOrDefault();

                    // If there is an existing item line increase it's quantity and return.
                    if (itemLine != null)
                    {
                        itemLine.Quantity++;
                        _context.SaveChanges();
                        return Ok();
                    }
                    // If there is not an already exisiting item line make a new one.
                    else
                    {
                        var newItemLine = new ShoppingCartLine();

                        newItemLine.ShoppingCartId = selectedCart.Id;
                        newItemLine.ItemId = (int)itemId;
                        newItemLine.Quantity = 1;

                        _context.ShoppingCartLines.Add(newItemLine);
                        _context.SaveChanges();
                        return Ok();
                    }
                }
                return BadRequest("No selected cart");
            }
            return BadRequest("User not logged in");
        }

        [HttpDelete]
        public IActionResult RemoveItem([FromQuery] int? itemId)
        {
            if (itemId == null)
                return BadRequest("No item id given");

            int? userId = HttpContext.Session.GetInt32("UserId");

            // Get the user's account from the database.
            Account userAccount = _context.Accounts.Find(userId);

            if (userAccount != null)
            {
                ShoppingCart? selectedCart = _context.ShoppingCarts.Find(userAccount.SelectedCart);

                if (selectedCart != null)
                {
                    // Get the Shopping cart line which connects the item being removed and the selected cart if it exists.
                    var itemLine = _context.ShoppingCartLines.Where(l => l.ShoppingCartId == selectedCart.Id && l.ItemId == itemId).FirstOrDefault();

                    // If there is an existing item line reduce it's quantity and return.
                    if (itemLine != null)
                    {

Views/Home/Index.cshtml
@model Tuple<IEnumerable<Item>, IEnumerable<Item>?>;
@{
    var username = ViewBag.Username;
    string welcomeMsg = "Welcome user";

    if (username != null)
        welcomeMsg = $"Welcome {username}";

    var errorMsg = ViewBag.ErrorMessage;
}


<!DOCTYPE html>

<html>
    <div class="container">
        <div class="row">
            <div class="col-5">
                <img src="~/Sams Warehouse Shopping Cart.svg" alt="Shopping cart img" style="max-width: 150px;" />
            </div>
            <div class="col-4">
                <div class="d-inline" p-2 style="font-size: xx-large">@welcomeMsg</div>
                <div style="font-size:xx-large; color:red">@errorMsg</div>

            </div>

            <div class="col-3 d-flex justify-content-around align-items-center">
                <input type="button" id="btnLogin" value="Login" />
                <input type="button" id="btnSignup" value="Sign up" />
            </div>
            <div class="col border border-dark bg-colour-1" >
                <a class="nav-link text-dark d-inline" asp-area="" asp-controller="About" asp-action="Index">About us</a>
                <a class="nav-link text-dark d-inline" asp-area="" asp-controller="Settings" asp-action="Index">Settings</a>
                <a class="nav-link text-dark d-inline" asp-area="" asp-controller="ShoppingCart" asp-action="Index">Manage shopping lists</a>
            </div>

        </div>
        <div class="row bg-colour-0 border border-4 border-dark" style="margin-top: 20px;">
            <div class="col-2" style="font-size: xx-large">Items</div>
            <div class="col-10 d-flex" style="justify-content-end">
                <div class="container">
                    <div class="row justify-content-end">
                        <div class="col-10 d-flex justify-content-end">
                            <div class="d-flex flex-column justify-content-center">
                                Selected shopping cart: @ViewData["SelectedCart"]
                                <input type="button" value="Show cart contents" id="btnCartShow" />
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>

        <!--Cards containing the items-->
        <!--Take the contents of item one which is a list of all the items in the database and display it as rows of cards-->
       <div class="row center justify-content-around" style="margin-top:50px">
            @foreach (var i in Model.Item1){
                <div class="col-3" style="margin-bottom: 20px; margin-left:10px; margin-right:10px">
                    <div class="card" style="width: 18rem; height:11rem">
                        <div class="card-body">
                            <h5 class="card-title">@i.Name</h5>
                            <p class="card-text">@i.Unit</p>
                            <p class="card-text">$@i.Price</p>
                                <input class="btn-primary" type="button" id="AddHome" itemId="@i.Id" value="Add to cart">
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>


    <!-- Login/signup modal -->
    <div class="modal fade" id="m" tabindex="-1">
        <div class="modal-dialog">
            <div class="modal-content" id="mContent"></div>
        </div>
    </div>

    <!-- Shopping cart modal -->
    <div class="modal right fade" id="mCart" tabindex="-1" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content" id="mCartContent"></div>
        </div>
    </div>




    <script src="~/js//CartModalDisplay.js" asp-append-version="true"></script>
    
    <script src="~/js/HomeAddItems.js" asp-append-version="true"></script>
    <script src="~/js/User.js" asp-append-version="true"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>


</html>